### ISSUE TITLE
Specimen tab Bug report

### ISSUE THREAD

**Issue by OlesjaSenkiv** [geocollections/geokogud#108]

**Comment by OlesjaSenkiv** [comment]
Bug #1. Specimen >> specimen nr incorrect

![image](https://cloud.githubusercontent.com/assets/25752623/25161505/fe19be52-24c4-11e7-87e7-1989dca0599d.png)

**Comment by OlesjaSenkiv** [comment]
bug1 fixed

**Comment by OlesjaSenkiv** [comment]
bug2.Specimen >> adminUnit searchCriteria is not working

**Comment by OlesjaSenkiv** [comment]
bug3.Common bug for all does not contain and does not exact is not working with multiseaech fields. Currently solution - do not show as search criteria.

**Comment by OlesjaSenkiv** [comment]
bug4. Specimen >> main search Map is not working because API do not return locality_id

**Comment by OlesjaSenkiv** [comment]
bug5. Specimen >> collection number search currently is not working due to  API 500 ERROR

**Comment by OlesjaSenkiv** [comment]
bug6. Specimen >> if date is chosen and some more field reference multisearch request is incorrect

https://api.arendus.geokogud.info/specimen/?paginate_by=30&page=1&order_by=-id&format=json&date_added__gte=2000-12-31T22:00:00.000Z&date_added__lte=2001-12-31T22:00:00.000Z&multi_search=value:Viira, 1975;fields:specimenreference__reference__author,specimenreference__reference__title,agent_collected__surename;lookuptype:icontains&fields=id,specimen_nr,specimen_id,coll__number,coll_id,specimenidentification__name,locality__locality,locality__locality_en,depth,depth_interval,stratigraphy__stratigraphy,stratigraphy__stratigraphy_en,lithostratigraphy__stratigraphy,lithostratigraphy__stratigraphy_en,stratigraphy_free,part,original_status__value,original_status__value_en,agent_collected__agent,agent_collected__forename,agent_collected__surename,database__name_en

**Comment by OlesjaSenkiv** [comment]
bug6. Specimen >> detail form translation for related_data is missing

**Comment by OlesjaSenkiv** [comment]
bug7. Specimen >> detail form images are missing

**Comment by OlesjaSenkiv** [comment]
bug8. Speciment >> sorting in all fields except id is incorrect.

**Comment by urtson** [comment]
Added specimenreference__reference__reference to API, which contains the
string "Viira, 1975". Use that field in multi_search.

**Comment by PrintScr** [comment]
@urtson 
Could you please also add to specimen_reference reference_id field? (currently there is only available id of associative table...)

**Comment by urtson** [comment]
Added reference_id to specimen_reference

**Comment by PrintScr** [comment]
@urtson 
I am sorry, but it is not present in specimen related data table...
https://api.arendus.geokogud.info/specimen/4939?related_data=specimen_reference

**Comment by urtson** [comment]
Ok, added it also to default fields
