### ISSUE TITLE
Soil sites search: server side

### ISSUE THREAD

**Issue by arturgummel** [geocollections/geokogud#24]
As a user, I would like to have soil sites search.

Acceptance criteria:
1. REST endpoint for the client is available.
2. Search works according to the functional requirements.

**Comment by PrintScr** [comment]
API does not provide required functionality for soil search. Documented here:
https://github.com/geocollections/geokogud/wiki/Impediment-list

**Comment by PrintScr** [comment]
Currently due to API limitations it is not possible neither to search by following fields nor show them in results: is_deep (Kas on sügavkaeve?) and transect (Transekt). Moreover, it is not possible to show transect_point.
