### ISSUE TITLE
Analyses search: server side

### ISSUE THREAD

**Issue by arturgummel** [geocollections/geokogud#27]
As a user, I would like to have analyses search.

Acceptance criteria:

1. REST endpoint for the client is available.
2. Search works according to the functional requirements.

**Comment by arturgummel** [comment]
commit acadf7313e3da4dd8fe2193b6fd3584f0f0152ad

**Comment by PrintScr** [comment]
Will take it over and see what fields are still missing.

**Comment by PrintScr** [comment]
@urtson 
Hi, I would be grateful if you could add **database__acronym** field :)
