### ISSUE TITLE
Stratigraphic units search: server side

### ISSUE THREAD

**Issue by arturgummel** [geocollections/geokogud#28]
As a user, I would like to have stratigraphic units search.

Acceptance criteria:

1. REST endpoint for the client is available.
2. Search works according to the functional requirements.

**Comment by PrintScr** [comment]
Reworking current implementation of the server-side search.

**Comment by PrintScr** [comment]
I need API to have following fields:
stratigraphy.age_base
stratigraphy.lithology
stratigraphy.author_free

**Comment by PrintScr** [comment]
Following fields are missing (for modal):

stratigraphy.region
stratigraphy.author
stratigraphy.author_free
stratigraphy.etymon
stratigraphy.original_locality
stratigraphy.age_top
stratigraphy.age_base
stratigraphy.max_thickness
stratigraphy.color_code_cgmw
stratigraphy.color_code_usgs
stratigraphy.remarks
stratigraphy -> reference.reference

**Comment by urtson** [comment]
API updated

**Comment by PrintScr** [comment]
Could you also please add stratigraphy->synonym.synonym and stratigraphy.lithology_en?

**Comment by arturgummel** [comment]
Could you please add following fields?
stratigraphy -> age_chronostratigraphy -> stratigraphy, stratigraphy_en
stratigraphy -> type -> list_stratigraphy_type -> value, value_en

**Comment by urtson** [comment]
API updated. You can get synonym field by querying related_data=stratigraphy_synonym
