### ISSUE TITLE
Samples search: server side

### ISSUE THREAD

**Issue by arturgummel** [geocollections/geokogud#32]
As a user, I would like to have samples search.

Acceptance criteria:

1. REST endpoint for the client is available.
2. Search works according to the functional requirements.

**Comment by PrintScr** [comment]
Some fields are still unavailable in search criteria, will look into it.

**Comment by PrintScr** [comment]
Could you please add following fields?
sample.number_field
sample->list_country.ISO_code
sample.asustusyksus
sample.asustusyksus_en
stratigraphy_free
sample->taxon_list.taxon
sample->taxon_list.frequency
sample -> analysis.analysis_method
sample -> analysis.method_details
sample -> analysis -> analysis_results.name
sample -> analysis -> analysis_results.value

**Comment by urtson** [comment]
API updated

**Comment by urtson** [comment]
API updated
