### ISSUE TITLE
Soil details dialogue: server side

### ISSUE THREAD

**Issue by PrintScr** [geocollections/geokogud#62]
As a user, I would like to have soil details dialogue.

Acceptance criteria:

1. Appropriate API request is formed in order to retrieve all the necessary information (as in the old system).

**Comment by PrintScr** [comment]
In order to fully implement this modal screen, I need to have access to **soil_horizon** table:
1. id
2. horizon_number
3. horizon
4. depth
5. transition_a
6. transition_b
7. korese_tyyp_a
8. korese_tyyp_b
9. korese_aste_1
10. korese_aste_2
11. granulometry_1
12. granulometry_2
13. remarks

**Comment by urtson** [comment]
API updated

**Comment by PrintScr** [comment]
Oh, could you also add soil_site_id to soil_horizon?
You could in addition add this table to SOIL related tables... And also sample table (fields: number_additional, soil_horizon, depth, depth_interval, remarks).

**Comment by urtson** [comment]
API updated
