### ISSUE TITLE
Photo archive details dialogue: server side

### ISSUE THREAD

**Issue by PrintScr** [geocollections/geokogud#64]
As a user, I would like to have photo archive details dialogue.

Acceptance criteria:

- Appropriate API request is formed in order to retrieve all the necessary information (as in the old system).

**Comment by PrintScr** [comment]
I need following additional fields from image endpoint in order to show an image on the dialog:
image->imageset.imageset_series
image->imageset.imageset_number

**Comment by PrintScr** [comment]
I need access to following fields in image endpoint:
copyright

**Comment by urtson** [comment]
API updated

**Comment by PrintScr** [comment]
Thank you for adding fields!
But I still need:
image->database.acronym

**Comment by urtson** [comment]
API updated
