### ISSUE TITLE
Localities details dialogue: server side

### ISSUE THREAD

**Issue by PrintScr** [geocollections/geokogud#69]
As a user, I would like to have localities details dialogue.

Acceptance criteria:

Details dialog displays identical data as in the old system.

**Comment by PrintScr** [comment]
I need API to have following fields:
locality.coord_system
locality.x
locality.y
locality.coord_det_precision
locality.coord_det_method
locality.coord_det_agent
locality.stratigraphy_top_free
locality.stratigraphy_base_free
locality.remarks
locality.user_added
locality.record_added
locality.record_changed

**Comment by urtson** [comment]
API updated

**Comment by PrintScr** [comment]
Thank you!
It would be great if you could add to related data references. Or add to references table locality_id...
