### ISSUE TITLE
Drill cores details dialog: server side

### ISSUE THREAD

**Issue by PrintScr** [geocollections/geokogud#80]
As a user, I would like to have drill cores units details dialogue.

Acceptance criteria:

Details dialog displays identical data as in the old system.

**Comment by PrintScr** [comment]
Please add following fields to API:

drillcore_en
locality_id
storage
drillcore->storage.address
drillcore->agent.agent
year
number_meters
remarks
maaament_pa_id (fox the link)

Thanks! <3

**Comment by urtson** [comment]
API updated

**Comment by PrintScr** [comment]
Thanks, but I still need to have:
drillcore->locality.locality and locality.locality_en (through drillcore.localityid)

**Comment by PrintScr** [comment]
There are also some fields missing in drillcore_box endpoint (no need to add these fields to related fields of drillcore->drillcore_box):
stratigraphy_top__id
stratigraphy_base__id

**Comment by urtson** [comment]
API updated
