### ISSUE TITLE
Analyze missing data for detail forms

### ISSUE THREAD

**Issue by OlesjaSenkiv** [geocollections/geokogud#92]

**Comment by OlesjaSenkiv** [comment]
Site_Soil >> I get correct result from API if is_deep value = false or choice is empty https://api.arendus.geokogud.info/soil_site/?paginate_by=30&page=1&order_by=id&format=json&is_deep__exact=false
otherwise 500 error

**Comment by OlesjaSenkiv** [comment]
Photo_Archive >> Search by Date is not possible due to 500 Error (date_taken is String type) https://api.arendus.geokogud.info/image/?paginate_by=30&page=1&order_by=id&format=json&multi_search=value:2007;fields:date_taken,date_taken_free;lookuptype:exact
I would make interval search for this field but it is not timestamp field

**Comment by urtson** [comment]
Fixed the issue with boolean values.
Filtering by date fields seems to be a problem, will work on that
